### ISSUE TITLE
[Bug] coverage does not detect .svelte files with jest v25

### ISSUE THREAD

**Issue by ksewo** [mihar-22/svelte-jester#1] opened 2020-02-13 18:03 UTC
Coverage does not work for .svelte files in v25, but it works fine for v24.

**Comment by mihar-22** [comment] 2020-02-14 06:16
I know a lot of people have been having issues generating coverage reports for `.svelte` files. In my case it throws a parser error because Jest uses Babel to parse the files before generating coverage reports. I haven't looked into this much, but my guess is we have to fork `@babel/parser` (because it doesn't accept plugins) and enable it to parse `.svelte` files.

**Comment by mihar-22** [comment] 2020-02-14 06:16
@ksewo do you get an error or does it simply not include the files in the coverage report?

**Comment by ksewo** [comment] 2020-02-14 09:45
@mihar-22 I do not get any error, just svelte files are not included into coverage. With jest v24 it is included, but still svelte files with <style> (atleast for me using svelte-preprocess and node-sass) are not included

**Comment by mihar-22** [comment] 2020-02-15 02:10
Updated comment above as I believe the issue is with Jest not this library, closing the issue for now until we find out more.

**Closed by mihar-22** 2020-02-15 02:10 UTC
Labels: bug

**Comment by marekdedic** [comment] 2021-12-02 22:18
Hi,
I am still getting this error on jest v27, does it work for you?

Thanks
