### ISSUE TITLE
Completely fails when using preprocessing

### ISSUE THREAD

**Issue by eden-omb** [mihar-22/svelte-jester#91] opened 2022-01-04 14:00 UTC
See [this repo](https://github.com/eden-omb/svelte-jester-preprocess-issue) for a minimal reproduction, just clone, install, and run tests. Full details for recreating the repo from scratch are included in the `README`.

The gist of it is, when I use the preprocessing flag, I get the following output:
```
 FAIL  src/routes/index-dom.spec.js
  ● Test suite failed to run

    TypeError: The "id" argument must be of type string. Received an instance of URL

      at node_modules/.pnpm/svelte-jester@2.1.5_jest@27.4.5+svelte@3.44.3/node_modules/svelte-jester/dist/transformer.cjs:79:118

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.534 s, estimated 2 s
Ran all test suites matching /src/i.
 ERROR  Test failed. See above for more details.
```

**Comment by binarious** [comment] 2022-01-14 09:37
I think the problem is `NODE_OPTIONS=--experimental-vm-modules` when running jest, because the call of `svelte-jester` in `jest.config.js` uses the `transformer.cjs` which uses `require` and this fails.

My workaround in `jest.config.js`:
```js
transform: {
  "^.+\\.svelte$": [
    "./node_modules/svelte-jester/dist/transformer.mjs",
    {
      "preprocess": true
    }
  ]
},
```

**Comment by eden-omb** [comment] 2022-01-22 15:44
@binarious Works for me. Leaving this issue open for prosperity until this solution is either unnecessary or documented somewhere more accessible.

**Comment by mihar-22** [comment] 2022-02-01 10:16
Should be fixed now 😄  Let us know if you run into any issues.

**Closed by mihar-22** 2022-02-01 10:16 UTC

**Comment by binarious** [comment] 2022-02-07 10:03
Maybe that's another bug, but when I change `./node_modules/svelte-jester/dist/transformer.mjs` back to `svelte-jester` I get the following error:
> Cannot find module 'file:///home/myuser/projects/myvendor/myapp/svelte.config.js'
    Require stack:
    - /home/myuser/projects/myvendor/myapp/node_modules/.pnpm/svelte-jester@2.3.1_jest@27.5.0+svelte@3.46.4/node_modules/svelte-jester/dist/transformer.cjs
